version: "3.8"
services:
  typing_trainer:
    build: .
    image: typing_trainer_image
    container_name: typing_trainer_container
    working_dir: /typing_speed_trainer
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_LOCATION=redis://redis:6379
    volumes:
      - .:/typing_speed_trainer
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: python typing_speed_trainer/manage.py runserver 0.0.0.0:8000
  redis:
    image: 'redis'