version: "3.8"
services:
  typing_trainer:
    build: .
    image: typing_trainer_image
    container_name: typing_trainer_container
    environment:
      - REDIS_LOCATION=redis://redis:6377
    ports:
      - "8888:8000"
    depends_on:
      - redis
      - random_words_api
    command: python typing_speed_trainer/manage.py runserver 0.0.0.0:8000
  redis:
    image: redis
    command: --port 6377
    ports:
      - "6377:6377"
  random_words_api:
    image: borisplaton/random_words
    container_name: random_words_container
    ports:
      - "8080:8000"
    command: python random_words/manage.py runserver 0.0.0.0:8000