version: "3.8"

services:
  typing_trainer:
    build: .
    image: typing_trainer_image
    container_name: typing_trainer_container
    ports:
      - "${HOST}:${HOST}"
    env_file:
      - .env
    depends_on:
      - random_words_api
      - redis
      - database
    volumes:
      - staticfiles:/staticfiles
      - media:/media
  random_words_api:
    image: borisplaton/random_words
    container_name: random_words_container
    ports:
      - "8080:8000"
    command: python random_words/manage.py runserver 0.0.0.0:8000
  redis:
    image: redis
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - database_data:/var/lib/postgresql/data/

volumes:
  database_data:
  staticfiles:
  media: