version: "3.8"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - dev_redis:/data
  random_words_api:
    image: borisplaton/random_words
    container_name: random_words_container
    ports:
      - "8080:8000"
    command: python random_words/manage.py runserver 0.0.0.0:8000
volumes:
  dev_redis: