# Generated by Django 4.0.5 on 2022-07-01 02:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='average_typo_amount',
        ),
        migrations.AlterField(
            model_name='statistic',
            name='attempts_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество попыток'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='average_accuracy',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Средняя точность набора текста'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='average_wpm',
            field=models.PositiveIntegerField(default=0, verbose_name='Среднее количество слов в минуту'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
