# Generated by Django 4.0.5 on 2022-10-31 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_rename_average_accuracy_statistic_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistic',
            options={'verbose_name': 'Statistics', 'verbose_name_plural': 'Statistics'},
        ),
    ]
